### ISSUE TITLE
Question: Find indexer and serach

### ISSUE THREAD

**Issue by jeroenslor** [OXXAS/CommerceStarterKit#31]
Hi,

For indexing and searching I use elasticsearch for my current commerce impl. Instead of implementing a custom ISearchIndexBuilder and a custom SearchProvider I just created a custom indexing job and for search used the elasticsearch api. The main reason for this was that I wanted to use the rich api that elasticsearch provides instead of the SearchProvider api.

I was wondering what the main reason was that you guys decided to do the same (not creating a search and index provider, but creating a custom job and use find api for search)? And also if you guys experienced any down sides of this impl?

**Comment by evest** [comment]
Hi Jeroen,
sorry for the late reply. The main reason for doing custom indexing and querying was to use the rich Find API to query the catalog and provide facets for lists. I guess this is about personal preference, but we felt that this was easier to work with than the built in search provider.

There are a few things to consider with this approach, and one is how to keep the index up to date when content change. Right now, we have a job to index the whole catalog, and also an [event handler](https://github.com/OXXAS/CommerceStarterKit/blob/master/src/web/Business/Initialization/IndexingEventInitialization.cs) for the content published event for catalog content.

This will not be triggered if the price is changed, neither if the inventory is changed. There is work in progress to move this to an [IChangeProcessor](https://github.com/OXXAS/CommerceStarterKit/blob/master/src/web/Business/FindCatalogIndexingChangeNotificationProcessor.cs) (the same process that the existing catalog indexer is using), but this has not been completed yet, This has the added benefit that it runs async, and buffers the events so we can index in a smarter way (if you do bulk import, you might not want to index every entry individually).

Beware that the UI searches uses the SearchProvider, so if you do not have one, you won't get good search for editors. We've worked around that implementing our own [FindProductUiSearchProvider](https://github.com/OXXAS/CommerceStarterKit/blob/master/src/web/Business/Search/FindProductSearchProvider.cs) that searches our own Find catalog in the different edit mode searches (there are at least three that uses that one).

Since we're using EPiServer Find, we also [add lots of conventions](https://github.com/OXXAS/CommerceStarterKit/blob/master/src/web/Business/Initialization/IndexingEventInitialization.cs) about what not to index, to have better control of the size of the index. If you run the standard Find content indexer, it will index all catalog content out of the box, but not in a way that we use.

You should also note that with one of the [latest](http://world.episerver.com/releases/episerver---update-55/) Find updates, more Commerce features has been added, like the possibility to link to products as best bets, improved indexing and [more](http://world.episerver.com/documentation/Items/Developers-Guide/EPiServer-Find/9/Integration/episerver-commerce/).
